package org.dog.spring.api.model;

public enum NeedmentsDog {
    HOUSE_WITH_GARDEN,
    PHYSIOTHERAPY,
    BEHAVIORIST,
    LOTS_OF_ACTIVITY,
    LITTLE_ACTIVITY,
    SPECIAL_FOOD,
    GOOD_FOR_ELDERLY_PEOPLE,
    RECOMMENDED_FOR_CHILDREN,
    NEED_MEDICINE_DOSAGE,
    FOR_EXPERIENCED_OWNER,
    FOR_BEGINNER_OWNERS,
    FOR_SMALL_FLATS
}
